name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: testsol
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgbd240ea4.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://orgbcfbfa2a.crm.dynamics.com
      CLIENT_ID: 83773476-a3b8-4b66-afa9-47308044ca5b
      TENANT_ID: 4ad526cf-cc88-435a-96d7-8b0a4c07f5e8      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
